# Generate Segmentation images based on NetSurfBottom

In [44]:
%matplotlib qt

import time
import copy
import numpy as np
from skimage.filters import gaussian

from tifffile import imread, imsave
import _pickle as pickle

import matplotlib.pyplot as plt

from spimagine import volfig, volshow
from spimagine import EllipsoidMesh, Mesh

%reload_ext autoreload
%autoreload 2

from Netsurface3dFromBottom import NetSurfBottom
from data4dBottom import Data4dBottom

from mpl_toolkits import mplot3d

## Load and Initialize

In [54]:
filenames = [ '/home/wissmann/Cell_croppedModel-0.0.1-3D_Sim-PSF(0.2 0.2 0.6) PXS(0.1 0.1 0.1).tif']

In [60]:
data = Data4dBottom( filenames, pixelsize=(1.,1.,1.), silent=False )
data.set_seg_params(K=40,max_delta_k=10,divx=2,divy=2,min_dist=0,max_dist=20,s=2)
objects = []
ecells = []

Dimensions of frame 0 :  (50, 99, 96)


In [61]:
max_rs = data.images[0].shape[0]

min_rs = 1

In [62]:
Ea = data.init_object("Ea")
objects.append(Ea)
ecells.append(Ea)

## Actual Segmentation

In [69]:
data.add_object_at( Ea, min_rs, max_rs, frame=0, frame_to=0, segment_it=True )

Added appearance for "Ea" in frame 0
Number of columns: 2352
2
c 0
c 2352
      Optimum energy:  1406388.0
      Nodes in/out:  188160 0


## Save Surface points to txt file

In [15]:
#fig = plt.figure()
#ax = plt.axes(projection='3d')
xdata = np.zeros(20000)
ydata = np.zeros(20000)
zdata = np.zeros(20000)
#(xdata,ydata,zdata)=
x=data.give_surface_points(0)
k=0
fh=open("test_2s.txt","w")

for i in x:
    xdata[k]=x[k][0]
    ydata[k]=x[k][1]
    zdata[k]=x[k][2]
    k+=1
    if float(zdata[k])==46.0:
        continue
    else:
        fh.write(str(i)[1:-1]+'\n')

xdata=xdata[xdata!=0]

#ax.scatter3D(xdata, ydata, zdata, c=zdata, cmap='Greens');

## Visualization

In [37]:
w = data.show_frame(0,show_surfaces=True,stackUnits=[1.,1.,1.],raise_window=True)
data.show_objects(ecells, show_surfaces=True, show_centers=False, colors=data.colors_gold)

[[   0    1   48]
 [   1    2   49]
 [   2    3   50]
 ...
 [2349 2348 2301]
 [2350 2349 2302]
 [2351 2350 2303]]
in get normals
(4512, 3)
(2352, 3)
(4512, 3, 3)
(4512, 3)
[   0    1    2 ... 2349 2350 2351]
(4704, 3)
(4512, 3)
(4512, 3, 3)
[[   0    1   48]
 [   1    2   49]
 [   2    3   50]
 ...
 [2349 2348 2301]
 [2350 2349 2302]
 [2351 2350 2303]]
in get normals
(4512, 3)
(2352, 3)
(4512, 3, 3)
(4512, 3)
[   0    1    2 ... 2349 2350 2351]
(4704, 3)
(4512, 3)
(4512, 3, 3)


In [73]:
b=[2, 3, 4, 5, 6, 7,-5]
for a in b:
    if a==3:
        print(1,a)
    if a>0:
        print(2,a)
    else: print(3)

2 2
1 3
2 3
2 4
2 5
2 6
2 7
3
