# Generate Segmentation images based on NetSurf3d

In [1]:
%matplotlib qt

import time
import copy
import numpy as np
from skimage.filters import gaussian

from tifffile import imread, imsave
import _pickle as pickle

import matplotlib.pyplot as plt

from spimagine import volfig, volshow
from spimagine import EllipsoidMesh, Mesh

%reload_ext autoreload
%autoreload 2

from Netsurface3d import NetSurf3d
from data4d import Data4d
from stitch_surfaces import StitchSurfaces

no scikit-tensor detected, so separable functions wont work
This is a python3 issue and can be resolved by:

git clone https://github.com/mnick/scikit-tensor.git
pip3 install scikit-tensor


## Load and Initialize

In [19]:
#filenames of images and of mask have to be in same order

#filenames = [ '/Users/wissmann/BobSeg/Cell_croppedModel-0.0.1-3D_Sim-PSF(0.2 0.2 0.6) PXS(0.1 0.1 0.1).tif']
#filenames = [ '/Users/wissmann/BobSeg/Cell_croppedModel-0.0.1-3D_Sim-PSF(0.2 0.2 0.6) PXS(0.1 0.1 0.1)-1.tif']
filenames = [ '/Users/wissmann/BobSeg/Vecad-flidsRed-48hpf.lif - fish1-48hpf-1.tif']
filenames_mask = ['/Users/wissmann/BobSeg/fish_mask.tif']
#filenames = [ '/Users/wissmann/BobSeg/easy2surfaces.tif']
#filenames_mask = [ '/Users/wissmann/BobSeg/easymask.tif']
#filenames = [ '/Users/wissmann/BobSeg/HyperStack.tif']
#filenames = [ '/Users/wissmann/BobSeg/HyperStack3.tif']
#filenames = [ '/Users/wissmann/BobSeg/debugdx.tif']
#filenames = ['/Users/wissmann/BobSeg/nonquadratictest.tif']

In [20]:
data = Data4d( filenames, filenames_mask, pixelsize=(1.,1.,1.), silent=False, plane=None )
data.set_seg_params(K=100,max_delta_k=2,dx=10,dy=10,surfaces=2,min_dist=2,max_dist=100) #min and nax dist in terms of k

Dimensions (z,y,x) of frame 0 :  (213, 738, 792)
Dimensions (z,y,x) of mask 0 :  (738, 792)


In [21]:
#between min_rs and max_rs the program will look for the surfaces
max_rs = data.images[0].shape[0]
min_rs = 0

In [22]:
Ea = data.init_object("Ea")

## Actual Segmentation

In [23]:
data.add_object_at( Ea, min_rs, max_rs, frame=0, frame_to=0, segment_it=True, plot_base_graph=False )

Added appearance for "Ea" in frame 0
Number of columns: 3038
Number of Surfaces: 2
c 0
c 303800
      Optimum energy:  396547.0
      Nodes in/out:  406143 201457


## Visualization

In [30]:
w = data.show_frame(0,show_surfaces=True,show_centers=False, stackUnits=[1.,1.,1.],raise_window=True,export=True,stitch=True)

s 0
s 1
stitching surfaces:  0 1
[array([ 10., 310.,  97.]), array([ 10., 320., 102.]), array([ 10., 330.,  97.]), array([ 10., 340.,  97.]), array([ 10., 350.,  97.]), array([ 20., 390.,  97.]), array([ 30., 390.,  93.]), array([ 30., 400.,  95.]), array([ 40., 400.,  95.]), array([ 40., 410., 100.]), array([ 50., 420., 102.]), array([ 80., 430., 104.]), array([110., 440., 108.]), array([120., 440., 112.]), array([130., 440., 117.]), array([140., 440., 121.]), array([150., 440., 125.]), array([170., 430., 129.]), array([190., 420., 134.]), array([200., 420., 138.]), array([220., 410., 142.]), array([230., 400., 146.]), array([240., 400., 151.]), array([240., 410., 155.]), array([240., 420., 157.]), array([230., 430., 157.]), array([230., 440., 157.]), array([220., 450., 159.]), array([220., 460., 155.]), array([220., 470., 155.]), array([210., 490., 159.]), array([210., 500., 159.]), array([210., 510., 161.]), array([210., 520., 161.]), array([210., 530., 164.]), array([210., 540., 15

/Users/wissmann/BobSeg/Netsurface3d.py:325: RuntimeWarning: invalid value encountered in true_divide
  arr[:,0] /= lens
/Users/wissmann/BobSeg/Netsurface3d.py:326: RuntimeWarning: invalid value encountered in true_divide
  arr[:,1] /= lens
/Users/wissmann/BobSeg/Netsurface3d.py:327: RuntimeWarning: invalid value encountered in true_divide
  arr[:,2] /= lens


## Save Surface points to txt file

In [59]:
#fig = plt.figure()
#ax = plt.axes(projection='3d')
xdata = np.zeros(20000)
ydata = np.zeros(20000)
zdata = np.zeros(20000)
#(xdata,ydata,zdata)=
x=np.array(data.give_surface_points(0))
print(x)
print(x.shape)

k=0
fh=open("test.txt","w")

for i in x[0]:
 #   xdata[k]=x[0][k][0]
 #   ydata[k]=x[0][k][1]
 #   zdata[k]=x[0][k][2]
    k+=1
    print(i[0])
    fh.write(str(i[0])+','+str(i[1])+','+str(i[2])+'\n')

xdata=xdata[xdata!=0]

#ax.scatter3D(xdata, ydata, zdata, c=zdata, cmap='Greens');

[[[ 0  0 11]
  [ 0  1 12]
  [ 0  2 12]
  ...
  [98 58 46]
  [98 59 46]
  [98 60 46]]]
(1, 12078, 3)
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7


51
51
51
51
51
51
51
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
57
57
57
57
57
57
57
57
57
57
57
57
57
57
57
57
57
57
57
57
57
5

2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
10
10
10
10
10
10
10
10
10

51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
5