# Generate Segmentation images based on NetSurfBottom

In [1]:
%matplotlib qt

import time
import copy
import numpy as np
from skimage.filters import gaussian

from tifffile import imread, imsave
import _pickle as pickle

import matplotlib.pyplot as plt

from spimagine import volfig, volshow
from spimagine import EllipsoidMesh, Mesh

%reload_ext autoreload
%autoreload 2

from Netsurface3dFromBottom import NetSurfBottom
from data4dBottom import Data4dBottom

no scikit-tensor detected, so separable functions wont work
This is a python3 issue and can be resolved by:

git clone https://github.com/mnick/scikit-tensor.git
pip3 install scikit-tensor


## Load and Initialize

In [2]:
filenames = [ '/Users/wissmann/BobSeg/Cell_croppedModel-0.0.1-3D_Sim-PSF(0.2 0.2 0.6) PXS(0.1 0.1 0.1).tif']
#filenames = [ '/Users/wissmann/BobSeg/easy2surfaces.tif']

In [23]:
data = Data4dBottom( filenames, pixelsize=(1.,1.,1.), silent=False )
data.set_seg_params(K=40,max_delta_k=2,divx=1,divy=1,min_dist=1,max_dist=40,s=2)
objects = []
ecells = []

Dimensions of frame 0 :  (50, 99, 96)
50
99
min dist 1


In [24]:
print(data.images[0].shape[0])
max_rs = data.images[0].shape[0]

min_rs = 0

50


In [25]:
Ea = data.init_object("Ea")
objects.append(Ea)
ecells.append(Ea)

## Actual Segmentation

In [26]:
data.add_object_at( Ea, min_rs, max_rs, frame=0, frame_to=0, segment_it=True )

Added appearance for "Ea" in frame 0
Number of columns: 9504
Number of Surfaces: 2
c 0
c 380160
      Optimum energy:  1829053.0
      Nodes in/out:  274264 486056


## Save Surface points to txt file

## Visualization

In [27]:
w = data.show_frame(0,show_surfaces=True,show_centers=False, stackUnits=[1.,1.,1.],raise_window=True)

s 0
[[   0    1   96]
 [   1    2   97]
 [   2    3   98]
 ...
 [9501 9500 9405]
 [9502 9501 9406]
 [9503 9502 9407]]
indices shape 18620
indices (18620, 3)
verts (9504, 3)
s 1
[[   0    1   96]
 [   1    2   97]
 [   2    3   98]
 ...
 [9501 9500 9405]
 [9502 9501 9406]
 [9503 9502 9407]]
indices shape 18620
indices (18620, 3)
verts (9504, 3)


INFO:spimagine.gui.glwidget | saving frame as /Users/wissmann/BobSeg/2surf_spim_out.png


In [16]:
#fig = plt.figure()
#ax = plt.axes(projection='3d')
xdata = np.zeros(20000)
ydata = np.zeros(20000)
zdata = np.zeros(20000)
#(xdata,ydata,zdata)=
x=data.give_surface_points(0)

k=0
fh=open("test_2s.txt","w")

for i in x:
    xdata[k]=x[k][0]
    ydata[k]=x[k][1]
    zdata[k]=x[k][2]
    k+=1
    if float(zdata[k])==46.0:
        continue
    else:
        fh.write(str(i)[1:-1]+'\n')

xdata=xdata[xdata!=0]

#ax.scatter3D(xdata, ydata, zdata, c=zdata, cmap='Greens');

IndexError: index 20000 is out of bounds for axis 0 with size 20000