# Generate Segmentation images based on NetSurf3d

In [4]:
%matplotlib qt

import time
import copy
import numpy as np
from skimage.filters import gaussian

from tifffile import imread, imsave
import _pickle as pickle

import matplotlib.pyplot as plt

from spimagine import volfig, volshow
from spimagine import EllipsoidMesh, Mesh

%reload_ext autoreload
%autoreload 2

from Netsurface3d import NetSurf3d
from data4d import Data4d

## Load and Initialize

In [5]:
#filenames of images and of mask have to be in same order

#filenames = [ '/Users/wissmann/BobSeg/Cell_croppedModel-0.0.1-3D_Sim-PSF(0.2 0.2 0.6) PXS(0.1 0.1 0.1).tif']
#filenames = [ '/Users/wissmann/BobSeg/Cell_croppedModel-0.0.1-3D_Sim-PSF(0.2 0.2 0.6) PXS(0.1 0.1 0.1)-1.tif']
filenames = [ '/Users/wissmann/BobSeg/Vecad-flidsRed-48hpf.lif - fish1-48hpf-1.tif']
filenames_mask = ['/Users/wissmann/BobSeg/fish_mask.tif']
#filenames = [ '/Users/wissmann/BobSeg/easy2surfaces.tif']
#filenames_mask = [ '/Users/wissmann/BobSeg/easymask.tif']
#filenames = [ '/Users/wissmann/BobSeg/HyperStack.tif']
#filenames = [ '/Users/wissmann/BobSeg/HyperStack3.tif']
#filenames = [ '/Users/wissmann/BobSeg/debugdx.tif']
#filenames = ['/Users/wissmann/BobSeg/nonquadratictest.tif']

In [6]:
data = Data4d( filenames, filenames_mask, pixelsize=(1.,1.,1.), silent=False, plane=None )
data.set_seg_params(K=40,max_delta_k=20,dx=20,dy=6,surfaces=2,min_dist=2,max_dist=40) #min and nax dist in terms of k

Dimensions (z,y,x) of frame 0 :  (213, 738, 792)
Dimensions (z,y,x) of mask 0 :  (738, 792)


In [7]:
#between min_rs and max_rs the program will look for the surfaces
max_rs = data.images[0].shape[0]
min_rs = 0

In [8]:
Ea = data.init_object("Ea")

## Actual Segmentation

In [9]:
data.add_object_at( Ea, min_rs, max_rs, frame=0, frame_to=0, segment_it=True, plot_base_graph=False )

Added appearance for "Ea" in frame 0
Number of columns: 2513
Number of Surfaces: 2
c 0
c 100520
      Optimum energy:  130138.0
      Nodes in/out:  129578 71462


## Visualization

In [11]:
w = data.show_frame(0,show_surfaces=True,show_centers=False, stackUnits=[1.,1.,1.],raise_window=True,export=True)

s 0
(2513, 3)
(4855, 3)
[ 20. 270.  26.]
[ 20. 276.  74.]
[ 20. 282.  95.]
[ 20. 288.  95.]
[ 20. 294.  85.]
[ 20. 300.  85.]
[ 20. 306. 101.]
[ 20. 312.  95.]
[ 20. 318.  95.]
[ 20. 324.  95.]
[ 20. 330.  95.]
[ 20. 336.  90.]
[ 20. 342.  85.]
[ 20. 348.  95.]
[ 20. 354.  85.]
[ 20. 360.  79.]
[ 20. 366.  26.]
[ 20. 372.  26.]
[ 20. 378.  26.]
[ 20. 384.  21.]
[ 20. 390.  37.]
[ 40. 228.  79.]
[ 40. 234.  85.]
[ 40. 240.  85.]
[ 40. 246.  95.]
[ 40. 252.  90.]
[ 40. 258.  95.]
[ 40. 264.  90.]
[ 40. 270.  95.]
[ 40. 276.  85.]
[ 40. 282.  95.]
[ 40. 288.  85.]
[ 40. 294.  95.]
[ 40. 300.  95.]
[ 40. 306.  95.]
[ 40. 312.  85.]
[ 40. 318.  85.]
[ 40. 324.  95.]
[ 40. 330.  74.]
[ 40. 336.  95.]
[ 40. 342.  74.]
[ 40. 348.  95.]
[ 40. 354.  95.]
[ 40. 360.  95.]
[ 40. 366.  95.]
[ 40. 372.  95.]
[ 40. 378.  90.]
[ 40. 384.  69.]
[ 40. 390.  69.]
[ 40. 396.  85.]
[ 40. 402.  79.]
[ 40. 408.  31.]
[ 60. 186.  85.]
[ 60. 192.  85.]
[ 60. 198.  90.]
[ 60. 204.  95.]
[ 60. 210.  95.]
[ 60. 2

[300. 174. 154.]
[300. 180. 159.]
[300. 186. 159.]
[300. 192. 165.]
[300. 198. 165.]
[300. 204. 165.]
[300. 210. 165.]
[300. 216. 165.]
[300. 222. 165.]
[300. 228. 170.]
[300. 234.  69.]
[300. 240. 170.]
[300. 246. 165.]
[300. 252. 175.]
[300. 258. 165.]
[300. 264. 170.]
[300. 270. 159.]
[300. 276. 165.]
[300. 282. 159.]
[300. 288. 159.]
[300. 294. 111.]
[300. 300. 159.]
[300. 306. 111.]
[300. 312. 111.]
[300. 318. 117.]
[300. 324. 117.]
[300. 330. 154.]
[300. 336. 165.]
[300. 342. 159.]
[300. 348. 159.]
[300. 354. 159.]
[300. 360. 165.]
[300. 366. 165.]
[300. 372. 165.]
[300. 378. 170.]
[300. 384. 170.]
[300. 390. 165.]
[300. 396. 170.]
[300. 402. 175.]
[300. 408. 175.]
[300. 414. 181.]
[300. 420. 175.]
[300. 426. 175.]
[300. 432. 175.]
[300. 438. 175.]
[300. 444. 175.]
[300. 450. 181.]
[300. 456. 181.]
[300. 462. 175.]
[300. 468. 175.]
[300. 474. 181.]
[300. 480. 175.]
[300. 486. 181.]
[300. 492. 181.]
[300. 498. 181.]
[300. 504. 181.]
[300. 510. 197.]
[300. 516. 197.]
[300. 522. 197

[400. 624. 170.]
[400. 630. 170.]
[400. 636. 191.]
[400. 642. 197.]
[400. 648. 165.]
[400. 654. 159.]
[400. 660. 186.]
[400. 666. 154.]
[400. 672. 191.]
[400. 678. 154.]
[400. 684. 175.]
[400. 690. 143.]
[400. 696. 143.]
[400. 702. 143.]
[400. 708. 181.]
[420. 156. 138.]
[420. 162. 138.]
[420. 168. 149.]
[420. 174. 159.]
[420. 180. 149.]
[420. 186. 149.]
[420. 192. 149.]
[420. 198. 165.]
[420. 204. 165.]
[420. 210. 165.]
[420. 216. 154.]
[420. 222. 159.]
[420. 228. 143.]
[420. 234. 154.]
[420. 240. 122.]
[420. 246. 143.]
[420. 252. 143.]
[420. 258. 143.]
[420. 264. 197.]
[420. 270. 143.]
[420. 276. 149.]
[420. 282. 149.]
[420. 288. 154.]
[420. 294. 154.]
[420. 300. 154.]
[420. 306. 149.]
[420. 312. 154.]
[420. 318. 197.]
[420. 324. 154.]
[420. 330. 159.]
[420. 336. 170.]
[420. 342. 165.]
[420. 348. 170.]
[420. 354. 175.]
[420. 360. 197.]
[420. 366. 175.]
[420. 372. 175.]
[420. 378. 181.]
[420. 384. 181.]
[420. 390. 186.]
[420. 396. 186.]
[420. 402. 186.]
[420. 408. 197.]
[420. 414. 197

[540. 558. 186.]
[540. 564. 197.]
[540. 570. 186.]
[540. 576. 186.]
[540. 582. 186.]
[540. 588. 181.]
[540. 594. 181.]
[540. 600. 181.]
[540. 606.  85.]
[540. 612. 175.]
[540. 618. 111.]
[540. 624. 175.]
[540. 630. 175.]
[540. 636. 170.]
[540. 642. 170.]
[540. 648. 170.]
[540. 654. 165.]
[540. 660. 165.]
[540. 666. 159.]
[540. 672.  69.]
[540. 678. 149.]
[540. 684. 149.]
[560. 306. 165.]
[560. 312. 165.]
[560. 318. 170.]
[560. 324. 170.]
[560. 330. 175.]
[560. 336. 175.]
[560. 342. 181.]
[560. 348. 186.]
[560. 354. 181.]
[560. 360. 181.]
[560. 366. 186.]
[560. 372. 186.]
[560. 378. 186.]
[560. 384. 191.]
[560. 390. 191.]
[560. 396. 191.]
[560. 402. 191.]
[560. 408. 191.]
[560. 414. 191.]
[560. 420. 197.]
[560. 426. 191.]
[560. 432. 197.]
[560. 438. 197.]
[560. 444. 197.]
[560. 450. 191.]
[560. 456. 101.]
[560. 462. 197.]
[560. 468. 191.]
[560. 474. 197.]
[560. 480. 197.]
[560. 486. 197.]
[560. 492. 197.]
[560. 498. 191.]
[560. 504. 191.]
[560. 510. 191.]
[560. 516. 191.]
[560. 522. 191

[740. 354. 186.]
[740. 360.  95.]
[740. 366.  95.]
[740. 372. 106.]
[740. 378. 106.]
[740. 384. 106.]
[740. 390. 106.]
[740. 396. 106.]
[740. 402. 106.]
[740. 408. 101.]
[740. 414. 106.]
[740. 420. 106.]
[740. 426. 191.]
[740. 432. 106.]
[740. 438. 106.]
[740. 444. 106.]
[740. 450. 117.]
[740. 456. 117.]
[740. 462. 106.]
[740. 468. 117.]
[740. 474. 127.]
[740. 480.  95.]
[740. 486. 127.]
[740. 492. 106.]
[740. 498. 106.]
[740. 504.  95.]
[740. 510. 181.]
[740. 516. 127.]
[740. 522. 181.]
[740. 528. 181.]
[740. 534. 181.]
[740. 540. 175.]
[740. 546.  95.]
[740. 552.  95.]
[740. 558. 138.]
[740. 564. 138.]
[740. 570. 143.]
[740. 576. 143.]
[740. 582. 159.]
[740. 588. 159.]
[740. 594. 106.]
[760. 372. 186.]
[760. 378. 186.]
[760. 384. 106.]
[760. 390. 106.]
[760. 396. 106.]
[760. 402. 191.]
[760. 408. 106.]
[760. 414.  95.]
[760. 420. 106.]
[760. 426. 106.]
[760. 432.  95.]
[760. 438. 106.]
[760. 444. 106.]
[760. 450.  95.]
[760. 456. 111.]
[760. 462. 191.]
[760. 468.  95.]
[760. 474. 106

[260. 126.  85.]
[260. 132.  69.]
[260. 138.  69.]
[260. 144.  63.]
[260. 150.  63.]
[260. 156.  58.]
[260. 162. 138.]
[260. 168.  58.]
[260. 174.  58.]
[260. 180.  53.]
[260. 186.  53.]
[260. 192. 159.]
[260. 198. 149.]
[260. 204.  53.]
[260. 210.  31.]
[260. 216.  63.]
[260. 222.  47.]
[260. 228.  47.]
[260. 234.  63.]
[260. 240.  42.]
[260. 246.  42.]
[260. 252.  53.]
[260. 258.  53.]
[260. 264.  47.]
[260. 270.  53.]
[260. 276.  37.]
[260. 282.  37.]
[260. 288.  42.]
[260. 294. 106.]
[260. 300. 106.]
[260. 306. 101.]
[260. 312.  95.]
[260. 318. 111.]
[260. 324.  95.]
[260. 330.  95.]
[260. 336.  95.]
[260. 342.  95.]
[260. 348. 133.]
[260. 354. 138.]
[260. 360. 138.]
[260. 366. 138.]
[260. 372.  74.]
[260. 378. 138.]
[260. 384. 138.]
[260. 390. 138.]
[260. 396. 133.]
[260. 402. 138.]
[260. 408. 127.]
[260. 414. 127.]
[260. 420. 127.]
[260. 426. 127.]
[260. 432. 122.]
[260. 438. 122.]
[260. 444. 117.]
[260. 450. 117.]
[260. 456. 111.]
[260. 462. 111.]
[260. 468. 106.]
[260. 474. 111

[360. 660. 117.]
[360. 666. 117.]
[360. 672. 122.]
[360. 678. 122.]
[360. 684. 127.]
[360. 690.  37.]
[360. 696.  31.]
[380. 114. 127.]
[380. 120. 138.]
[380. 126. 143.]
[380. 132. 159.]
[380. 138. 159.]
[380. 144. 111.]
[380. 150.  47.]
[380. 156. 111.]
[380. 162.  53.]
[380. 168.  42.]
[380. 174. 117.]
[380. 180. 106.]
[380. 186. 101.]
[380. 192. 106.]
[380. 198. 159.]
[380. 204. 111.]
[380. 210. 101.]
[380. 216. 106.]
[380. 222. 106.]
[380. 228. 106.]
[380. 234. 159.]
[380. 240. 149.]
[380. 246. 106.]
[380. 252. 106.]
[380. 258. 106.]
[380. 264. 106.]
[380. 270.  63.]
[380. 276. 111.]
[380. 282. 106.]
[380. 288. 101.]
[380. 294.  63.]
[380. 300. 106.]
[380. 306. 154.]
[380. 312. 106.]
[380. 318. 106.]
[380. 324. 106.]
[380. 330. 106.]
[380. 336. 111.]
[380. 342. 111.]
[380. 348. 106.]
[380. 354.  90.]
[380. 360. 106.]
[380. 366. 106.]
[380. 372. 106.]
[380. 378. 175.]
[380. 384. 175.]
[380. 390.  74.]
[380. 396. 143.]
[380. 402.  95.]
[380. 408. 186.]
[380. 414. 186.]
[380. 420. 101

[500. 696.  69.]
[520. 306. 143.]
[520. 312. 133.]
[520. 318. 127.]
[520. 324.  85.]
[520. 330.  85.]
[520. 336. 117.]
[520. 342. 117.]
[520. 348. 111.]
[520. 354. 111.]
[520. 360. 111.]
[520. 366.  95.]
[520. 372. 117.]
[520. 378. 149.]
[520. 384. 106.]
[520. 390. 106.]
[520. 396. 191.]
[520. 402. 101.]
[520. 408.  95.]
[520. 414. 138.]
[520. 420.  95.]
[520. 426. 106.]
[520. 432.  95.]
[520. 438.  85.]
[520. 444.  47.]
[520. 450.  79.]
[520. 456. 106.]
[520. 462.  95.]
[520. 468.  69.]
[520. 474.  95.]
[520. 480. 106.]
[520. 486. 133.]
[520. 492. 181.]
[520. 498.  85.]
[520. 504.  74.]
[520. 510.  79.]
[520. 516. 111.]
[520. 522. 106.]
[520. 528. 117.]
[520. 534.  79.]
[520. 540. 186.]
[520. 546.  85.]
[520. 552.  58.]
[520. 558.  69.]
[520. 564.  74.]
[520. 570.  63.]
[520. 576.  74.]
[520. 582.  69.]
[520. 588.  79.]
[520. 594.  69.]
[520. 600.  74.]
[520. 606.  85.]
[520. 612.  79.]
[520. 618.  74.]
[520. 624. 106.]
[520. 630. 111.]
[520. 636. 111.]
[520. 642. 111.]
[520. 648. 117

[700. 426.  95.]
[700. 432.  90.]
[700. 438.  95.]
[700. 444.  95.]
[700. 450.  95.]
[700. 456.  95.]
[700. 462.  95.]
[700. 468.  95.]
[700. 474.  95.]
[700. 480.  95.]
[700. 486.  95.]
[700. 492.  95.]
[700. 498.  90.]
[700. 504.  95.]
[700. 510.  95.]
[700. 516.  79.]
[700. 522.  85.]
[700. 528.  85.]
[700. 534.  95.]
[700. 540.  95.]
[700. 546.  85.]
[700. 552.  85.]
[700. 558.  95.]
[700. 564.  95.]
[700. 570.  95.]
[700. 576. 101.]
[700. 582.  95.]
[700. 588.  95.]
[700. 594.  90.]
[700. 600.  85.]
[700. 606.  95.]
[700. 612. 138.]
[700. 618.  95.]
[700. 624. 143.]
[720. 312.  95.]
[720. 318.  95.]
[720. 324. 133.]
[720. 330.  95.]
[720. 336.  95.]
[720. 342.  95.]
[720. 348.  95.]
[720. 354.  95.]
[720. 360.  95.]
[720. 366.  95.]
[720. 372.  95.]
[720. 378.  95.]
[720. 384.  95.]
[720. 390.  95.]
[720. 396. 101.]
[720. 402.  95.]
[720. 408.  95.]
[720. 414.  95.]
[720. 420.  95.]
[720. 426.  95.]
[720. 432.  95.]
[720. 438.  95.]
[720. 444.  95.]
[720. 450.  95.]
[720. 456.  95

## Save Surface points to txt file

In [59]:
#fig = plt.figure()
#ax = plt.axes(projection='3d')
xdata = np.zeros(20000)
ydata = np.zeros(20000)
zdata = np.zeros(20000)
#(xdata,ydata,zdata)=
x=np.array(data.give_surface_points(0))
print(x)
print(x.shape)

k=0
fh=open("test.txt","w")

for i in x[0]:
 #   xdata[k]=x[0][k][0]
 #   ydata[k]=x[0][k][1]
 #   zdata[k]=x[0][k][2]
    k+=1
    print(i[0])
    fh.write(str(i[0])+','+str(i[1])+','+str(i[2])+'\n')

xdata=xdata[xdata!=0]

#ax.scatter3D(xdata, ydata, zdata, c=zdata, cmap='Greens');

[[[ 0  0 11]
  [ 0  1 12]
  [ 0  2 12]
  ...
  [98 58 46]
  [98 59 46]
  [98 60 46]]]
(1, 12078, 3)
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7


51
51
51
51
51
51
51
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
57
57
57
57
57
57
57
57
57
57
57
57
57
57
57
57
57
57
57
57
57
5

2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
10
10
10
10
10
10
10
10
10

51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
51
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
52
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
53
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
54
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
55
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
56
5