# Generate Segmentation images based on NetSurfBottom

In [38]:
%matplotlib qt

import time
import copy
import numpy as np
from skimage.filters import gaussian

from tifffile import imread, imsave
import _pickle as pickle

import matplotlib.pyplot as plt

from spimagine import volfig, volshow
from spimagine import EllipsoidMesh, Mesh

%reload_ext autoreload
%autoreload 2

from Netsurface3dFromBottom import NetSurfBottom
from data4dBottom import Data4dBottom

from mpl_toolkits import mplot3d

## Load and Initialize

In [39]:
filenames = [ '/home/wissmann/Cell_croppedModel-0.0.1-3D_Sim-PSF(0.2 0.2 0.6) PXS(0.1 0.1 0.1).tif']

In [50]:
data = Data4dBottom( filenames, pixelsize=(1.,1.,1.), silent=False )
data.set_seg_params(K=40,max_delta_k=2,divx=1,divy=1,min_dist=20,max_dist=40,s=2)
objects = []
ecells = []

Dimensions of frame 0 :  (50, 99, 96)
50
99


In [51]:
max_rs = data.images[0].shape[0]

min_rs = 1

In [52]:
Ea = data.init_object("Ea")
objects.append(Ea)
ecells.append(Ea)

## Actual Segmentation

In [53]:
data.add_object_at( Ea, min_rs, max_rs, frame=0, frame_to=0, segment_it=True )

Added appearance for "Ea" in frame 0
Number of columns: 9504
Number of Surfaces: 2
c 0
c 380160
      Optimum energy:  2895900.0
      Nodes in/out:  412162 348158


## Save Surface points to txt file

In [11]:
#fig = plt.figure()
#ax = plt.axes(projection='3d')
xdata = np.zeros(20000)
ydata = np.zeros(20000)
zdata = np.zeros(20000)
#(xdata,ydata,zdata)=
x=data.give_surface_points(0)
'''
k=0
fh=open("test_2s.txt","w")

for i in x:
    xdata[k]=x[k][0]
    ydata[k]=x[k][1]
    zdata[k]=x[k][2]
    k+=1
    if float(zdata[k])==46.0:
        continue
    else:
        fh.write(str(i)[1:-1]+'\n')

xdata=xdata[xdata!=0]

#ax.scatter3D(xdata, ydata, zdata, c=zdata, cmap='Greens');
'''

(1, 1, 10)
(1, 2, 12)
(1, 3, 10)
(1, 4, 10)
(1, 5, 10)
(1, 6, 10)
(1, 7, 10)
(1, 8, 12)
(1, 9, 10)
(1, 10, 12)
(1, 11, 12)
(1, 12, 10)
(1, 13, 10)
(1, 14, 10)
(1, 15, 10)
(1, 16, 10)
(1, 17, 10)
(1, 18, 10)
(1, 19, 12)
(1, 20, 10)
(1, 21, 10)
(1, 22, 10)
(1, 23, 10)
(1, 24, 12)
(1, 25, 10)
(1, 26, 10)
(1, 27, 10)
(1, 28, 10)
(1, 29, 10)
(1, 30, 12)
(1, 31, 10)
(1, 32, 10)
(1, 33, 10)
(1, 34, 10)
(1, 35, 10)
(1, 36, 12)
(1, 37, 12)
(1, 38, 12)
(1, 39, 10)
(1, 40, 10)
(1, 41, 12)
(1, 42, 10)
(1, 43, 10)
(1, 44, 12)
(1, 45, 10)
(1, 46, 10)
(1, 47, 10)
(1, 48, 10)
(1, 49, 10)
(1, 50, 10)
(1, 51, 10)
(1, 52, 10)
(1, 53, 10)
(1, 54, 12)
(1, 55, 12)
(1, 56, 10)
(1, 57, 10)
(1, 58, 10)
(1, 59, 10)
(1, 60, 10)
(1, 61, 10)
(1, 62, 10)
(1, 63, 10)
(1, 64, 10)
(1, 65, 10)
(1, 66, 10)
(1, 67, 10)
(1, 68, 10)
(1, 69, 10)
(1, 70, 10)
(1, 71, 10)
(1, 72, 10)
(1, 73, 10)
(1, 74, 10)
(1, 75, 10)
(1, 76, 10)
(1, 77, 12)
(1, 78, 10)
(1, 79, 10)
(1, 80, 12)
(1, 81, 10)
(1, 82, 10)
(1, 83, 10)
(1, 84, 13)
(

(15, 47, 15)
(15, 48, 13)
(15, 49, 13)
(15, 50, 12)
(15, 51, 13)
(15, 52, 13)
(15, 53, 13)
(15, 54, 13)
(15, 55, 13)
(15, 56, 14)
(15, 57, 14)
(15, 58, 15)
(15, 59, 13)
(15, 60, 12)
(15, 61, 13)
(15, 62, 14)
(15, 63, 13)
(15, 64, 15)
(15, 65, 14)
(15, 66, 15)
(15, 67, 14)
(15, 68, 15)
(15, 69, 15)
(15, 70, 14)
(15, 71, 15)
(15, 72, 16)
(15, 73, 16)
(15, 74, 16)
(15, 75, 16)
(15, 76, 15)
(15, 77, 16)
(15, 78, 16)
(15, 79, 14)
(15, 80, 16)
(15, 81, 16)
(15, 82, 16)
(15, 83, 16)
(15, 84, 16)
(15, 85, 16)
(15, 86, 15)
(15, 87, 15)
(15, 88, 15)
(15, 89, 13)
(15, 90, 15)
(15, 91, 13)
(15, 92, 12)
(15, 93, 12)
(15, 94, 10)
(15, 95, 10)
(15, 96, 10)
(16, 1, 10)
(16, 2, 10)
(16, 3, 12)
(16, 4, 10)
(16, 5, 10)
(16, 6, 12)
(16, 7, 12)
(16, 8, 10)
(16, 9, 12)
(16, 10, 10)
(16, 11, 12)
(16, 12, 13)
(16, 13, 14)
(16, 14, 13)
(16, 15, 13)
(16, 16, 12)
(16, 17, 14)
(16, 18, 13)
(16, 19, 14)
(16, 20, 12)
(16, 21, 14)
(16, 22, 15)
(16, 23, 15)
(16, 24, 13)
(16, 25, 15)
(16, 26, 14)
(16, 27, 16)
(16, 28,

(29, 49, 24)
(29, 50, 24)
(29, 51, 25)
(29, 52, 24)
(29, 53, 24)
(29, 54, 24)
(29, 55, 24)
(29, 56, 24)
(29, 57, 24)
(29, 58, 24)
(29, 59, 23)
(29, 60, 23)
(29, 61, 24)
(29, 62, 24)
(29, 63, 24)
(29, 64, 24)
(29, 65, 23)
(29, 66, 23)
(29, 67, 24)
(29, 68, 24)
(29, 69, 24)
(29, 70, 23)
(29, 71, 21)
(29, 72, 21)
(29, 73, 21)
(29, 74, 21)
(29, 75, 21)
(29, 76, 21)
(29, 77, 20)
(29, 78, 20)
(29, 79, 20)
(29, 80, 20)
(29, 81, 18)
(29, 82, 19)
(29, 83, 18)
(29, 84, 16)
(29, 85, 16)
(29, 86, 16)
(29, 87, 16)
(29, 88, 14)
(29, 89, 14)
(29, 90, 12)
(29, 91, 13)
(29, 92, 10)
(29, 93, 10)
(29, 94, 13)
(29, 95, 12)
(29, 96, 10)
(30, 1, 12)
(30, 2, 10)
(30, 3, 12)
(30, 4, 10)
(30, 5, 10)
(30, 6, 12)
(30, 7, 10)
(30, 8, 13)
(30, 9, 12)
(30, 10, 14)
(30, 11, 15)
(30, 12, 15)
(30, 13, 15)
(30, 14, 16)
(30, 15, 18)
(30, 16, 19)
(30, 17, 18)
(30, 18, 18)
(30, 19, 20)
(30, 20, 20)
(30, 21, 19)
(30, 22, 20)
(30, 23, 20)
(30, 24, 21)
(30, 25, 21)
(30, 26, 21)
(30, 27, 21)
(30, 28, 21)
(30, 29, 23)
(30, 30,

(41, 50, 30)
(41, 51, 30)
(41, 52, 31)
(41, 53, 30)
(41, 54, 31)
(41, 55, 30)
(41, 56, 31)
(41, 57, 31)
(41, 58, 31)
(41, 59, 30)
(41, 60, 30)
(41, 61, 29)
(41, 62, 29)
(41, 63, 30)
(41, 64, 27)
(41, 65, 29)
(41, 66, 27)
(41, 67, 27)
(41, 68, 26)
(41, 69, 26)
(41, 70, 26)
(41, 71, 25)
(41, 72, 25)
(41, 73, 25)
(41, 74, 24)
(41, 75, 24)
(41, 76, 24)
(41, 77, 21)
(41, 78, 23)
(41, 79, 20)
(41, 80, 20)
(41, 81, 20)
(41, 82, 19)
(41, 83, 19)
(41, 84, 16)
(41, 85, 16)
(41, 86, 15)
(41, 87, 13)
(41, 88, 13)
(41, 89, 10)
(41, 90, 13)
(41, 91, 12)
(41, 92, 13)
(41, 93, 10)
(41, 94, 12)
(41, 95, 10)
(41, 96, 10)
(42, 1, 12)
(42, 2, 12)
(42, 3, 10)
(42, 4, 13)
(42, 5, 12)
(42, 6, 14)
(42, 7, 12)
(42, 8, 14)
(42, 9, 15)
(42, 10, 16)
(42, 11, 16)
(42, 12, 16)
(42, 13, 18)
(42, 14, 20)
(42, 15, 19)
(42, 16, 19)
(42, 17, 20)
(42, 18, 20)
(42, 19, 21)
(42, 20, 21)
(42, 21, 21)
(42, 22, 23)
(42, 23, 24)
(42, 24, 24)
(42, 25, 25)
(42, 26, 25)
(42, 27, 26)
(42, 28, 26)
(42, 29, 26)
(42, 30, 26)
(42, 31,

(57, 14, 20)
(57, 15, 20)
(57, 16, 21)
(57, 17, 23)
(57, 18, 23)
(57, 19, 23)
(57, 20, 24)
(57, 21, 23)
(57, 22, 25)
(57, 23, 25)
(57, 24, 25)
(57, 25, 25)
(57, 26, 27)
(57, 27, 27)
(57, 28, 27)
(57, 29, 27)
(57, 30, 27)
(57, 31, 30)
(57, 32, 30)
(57, 33, 31)
(57, 34, 31)
(57, 35, 32)
(57, 36, 32)
(57, 37, 34)
(57, 38, 32)
(57, 39, 32)
(57, 40, 34)
(57, 41, 34)
(57, 42, 34)
(57, 43, 35)
(57, 44, 36)
(57, 45, 35)
(57, 46, 35)
(57, 47, 35)
(57, 48, 36)
(57, 49, 35)
(57, 50, 34)
(57, 51, 34)
(57, 52, 35)
(57, 53, 35)
(57, 54, 34)
(57, 55, 34)
(57, 56, 34)
(57, 57, 32)
(57, 58, 34)
(57, 59, 34)
(57, 60, 32)
(57, 61, 31)
(57, 62, 31)
(57, 63, 31)
(57, 64, 31)
(57, 65, 30)
(57, 66, 29)
(57, 67, 29)
(57, 68, 27)
(57, 69, 27)
(57, 70, 27)
(57, 71, 26)
(57, 72, 25)
(57, 73, 26)
(57, 74, 25)
(57, 75, 24)
(57, 76, 24)
(57, 77, 23)
(57, 78, 21)
(57, 79, 21)
(57, 80, 20)
(57, 81, 18)
(57, 82, 19)
(57, 83, 16)
(57, 84, 18)
(57, 85, 16)
(57, 86, 14)
(57, 87, 12)
(57, 88, 12)
(57, 89, 14)
(57, 90, 13)

(67, 53, 32)
(67, 54, 32)
(67, 55, 32)
(67, 56, 32)
(67, 57, 32)
(67, 58, 32)
(67, 59, 31)
(67, 60, 31)
(67, 61, 31)
(67, 62, 30)
(67, 63, 31)
(67, 64, 30)
(67, 65, 29)
(67, 66, 29)
(67, 67, 27)
(67, 68, 27)
(67, 69, 27)
(67, 70, 27)
(67, 71, 25)
(67, 72, 25)
(67, 73, 25)
(67, 74, 23)
(67, 75, 24)
(67, 76, 23)
(67, 77, 23)
(67, 78, 21)
(67, 79, 20)
(67, 80, 20)
(67, 81, 19)
(67, 82, 20)
(67, 83, 18)
(67, 84, 16)
(67, 85, 16)
(67, 86, 15)
(67, 87, 15)
(67, 88, 14)
(67, 89, 13)
(67, 90, 13)
(67, 91, 12)
(67, 92, 12)
(67, 93, 13)
(67, 94, 12)
(67, 95, 10)
(67, 96, 12)
(68, 1, 10)
(68, 2, 13)
(68, 3, 10)
(68, 4, 13)
(68, 5, 14)
(68, 6, 15)
(68, 7, 14)
(68, 8, 16)
(68, 9, 16)
(68, 10, 16)
(68, 11, 19)
(68, 12, 18)
(68, 13, 19)
(68, 14, 20)
(68, 15, 20)
(68, 16, 20)
(68, 17, 20)
(68, 18, 21)
(68, 19, 23)
(68, 20, 21)
(68, 21, 23)
(68, 22, 24)
(68, 23, 25)
(68, 24, 25)
(68, 25, 25)
(68, 26, 25)
(68, 27, 26)
(68, 28, 26)
(68, 29, 27)
(68, 30, 27)
(68, 31, 27)
(68, 32, 27)
(68, 33, 29)
(68, 34,

(83, 17, 16)
(83, 18, 16)
(83, 19, 18)
(83, 20, 18)
(83, 21, 19)
(83, 22, 19)
(83, 23, 18)
(83, 24, 20)
(83, 25, 20)
(83, 26, 20)
(83, 27, 20)
(83, 28, 20)
(83, 29, 21)
(83, 30, 21)
(83, 31, 21)
(83, 32, 21)
(83, 33, 23)
(83, 34, 21)
(83, 35, 23)
(83, 36, 23)
(83, 37, 23)
(83, 38, 23)
(83, 39, 23)
(83, 40, 23)
(83, 41, 24)
(83, 42, 24)
(83, 43, 24)
(83, 44, 25)
(83, 45, 24)
(83, 46, 24)
(83, 47, 24)
(83, 48, 24)
(83, 49, 25)
(83, 50, 24)
(83, 51, 24)
(83, 52, 25)
(83, 53, 26)
(83, 54, 25)
(83, 55, 26)
(83, 56, 24)
(83, 57, 26)
(83, 58, 25)
(83, 59, 25)
(83, 60, 26)
(83, 61, 25)
(83, 62, 25)
(83, 63, 25)
(83, 64, 24)
(83, 65, 24)
(83, 66, 25)
(83, 67, 24)
(83, 68, 23)
(83, 69, 23)
(83, 70, 23)
(83, 71, 23)
(83, 72, 21)
(83, 73, 21)
(83, 74, 21)
(83, 75, 21)
(83, 76, 20)
(83, 77, 20)
(83, 78, 20)
(83, 79, 19)
(83, 80, 19)
(83, 81, 18)
(83, 82, 18)
(83, 83, 18)
(83, 84, 16)
(83, 85, 15)
(83, 86, 15)
(83, 87, 14)
(83, 88, 14)
(83, 89, 12)
(83, 90, 12)
(83, 91, 10)
(83, 92, 10)
(83, 93, 10)

(98, 76, 24)
(98, 77, 24)
(98, 78, 25)
(98, 79, 25)
(98, 80, 25)
(98, 81, 24)
(98, 82, 24)
(98, 83, 24)
(98, 84, 23)
(98, 85, 23)
(98, 86, 23)
(98, 87, 21)
(98, 88, 19)
(98, 89, 20)
(98, 90, 19)
(98, 91, 19)
(98, 92, 19)
(98, 93, 18)
(98, 94, 19)
(98, 95, 19)
(98, 96, 18)
(99, 1, 20)
(99, 2, 20)
(99, 3, 20)
(99, 4, 20)
(99, 5, 20)
(99, 6, 20)
(99, 7, 20)
(99, 8, 20)
(99, 9, 20)
(99, 10, 20)
(99, 11, 20)
(99, 12, 20)
(99, 13, 20)
(99, 14, 20)
(99, 15, 21)
(99, 16, 20)
(99, 17, 20)
(99, 18, 20)
(99, 19, 20)
(99, 20, 20)
(99, 21, 20)
(99, 22, 20)
(99, 23, 21)
(99, 24, 23)
(99, 25, 20)
(99, 26, 20)
(99, 27, 23)
(99, 28, 21)
(99, 29, 20)
(99, 30, 23)
(99, 31, 21)
(99, 32, 24)
(99, 33, 24)
(99, 34, 24)
(99, 35, 23)
(99, 36, 24)
(99, 37, 25)
(99, 38, 24)
(99, 39, 25)
(99, 40, 25)
(99, 41, 25)
(99, 42, 26)
(99, 43, 25)
(99, 44, 24)
(99, 45, 25)
(99, 46, 26)
(99, 47, 27)
(99, 48, 26)
(99, 49, 27)
(99, 50, 26)
(99, 51, 27)
(99, 52, 26)
(99, 53, 27)
(99, 54, 27)
(99, 55, 29)
(99, 56, 29)
(99, 57,

'\nk=0\nfh=open("test_2s.txt","w")\n\nfor i in x:\n    xdata[k]=x[k][0]\n    ydata[k]=x[k][1]\n    zdata[k]=x[k][2]\n    k+=1\n    if float(zdata[k])==46.0:\n        continue\n    else:\n        fh.write(str(i)[1:-1]+\'\n\')\n\nxdata=xdata[xdata!=0]\n\n#ax.scatter3D(xdata, ydata, zdata, c=zdata, cmap=\'Greens\');\n'

## Visualization

In [54]:
w = data.show_frame(0,show_surfaces=True,show_centers=False, stackUnits=[1.,1.,1.],raise_window=True)
#data.show_objects(ecells, show_surfaces=True, show_centers=False, colors=data.colors_gold)

s 0
[[   0    1   96]
 [   1    2   97]
 [   2    3   98]
 ...
 [9501 9500 9405]
 [9502 9501 9406]
 [9503 9502 9407]]
indices shape 18620
indices (18620, 3)
verts (9504, 3)
s 1
[[   0    1   96]
 [   1    2   97]
 [   2    3   98]
 ...
 [9501 9500 9405]
 [9502 9501 9406]
 [9503 9502 9407]]
indices shape 18620
indices (18620, 3)
verts (9504, 3)
